#pragma once

#ifndef ARC_DRIVE_LIB_VERSION_HPP
#define ARC_DRIVE_LIB_VERSION_HPP

#define ARC_DRIVE_LIB_MAJOR_VERSION 0
#define ARC_DRIVE_LIB_MINOR_VERSION 0
#define ARC_DRIVE_LIB_PATCH_VERSION 0
#define ARC_DRIVE_LIB_BUILD_NUMBER 1
#define ARC_DRIVE_LIB_BUILD_TYPE "alpha"
#define ARC_DRIVE_LIB_REVISION_NUMBER 0

#endif // !ARC_DRIVE_LIB_VERSION_HPP