#pragma once

#ifndef PROJECT_DRIVE_MANAGER_VERSION_HPP
#define PROJECT_DRIVE_MANAGER_VERSION_HPP

#define PROJECT_DRIVE_MANAGER_MAJOR_VERSION 0
#define PROJECT_DRIVE_MANAGER_MINOR_VERSION	1
#define PROJECT_DRIVE_MANAGER_PATCH_VERSION 0
#define PROJECT_DRIVE_MANAGER_REVISION_NUMBER 0
#define PROJECT_DRIVE_MANAGER_BUILD_NUMBER 3
#define PROJECT_DRIVE_MANAGER_BUILD_TYPE "alpha"

#endif // !PROJECT_DRIVE_MANAGER_VERSION_HPP