#pragma once

#ifndef MANAGER_CONFIG_VERSION_HPP
#define MANAGER_CONFIG_VERSION_HPP

#define MANAGER_CONFIG_MAJOR_VERSION 	0
#define MANAGER_CONFIG_MINOR_VERSION	3
#define MANAGER_CONFIG_PATCH_VERSION 	0
#define MANAGER_CONFIG_REVISION_NUMBER 	0
#define MANAGER_CONFIG_BUILD_NUMBER 	6
#define MANAGER_CONFIG_BUILD_TYPE 		"alpha"

#endif // !MANAGER_CONFIG_VERSION_HPP